name: Deploy to Server

on:
  push:
    branches: [ main ]

env:
  # Build
  TARGET_ARCH: amd64  # GitHub Actions runs on AMD64
  APP_FOLDER: ~/apps/bible-bot

  # Health check
  VM_HOST: ${{ secrets.SSH_HOST }}

  # Run environment
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_TARGET_CHAT_ID: ${{ secrets.TELEGRAM_TARGET_CHAT_ID }}
  TELEGRAM_STORAGE_CHAT_ID: ${{ secrets.TELEGRAM_STORAGE_CHAT_ID }}
  ADMIN_USER: ${{ secrets.ADMIN_USER }}
  ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

  TZ: Europe/Moscow
#   DB_PATH: ~/apps/bible-bot/data/bible.db # TODO: A little bit risky

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy with Docker
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            export TARGET_ARCH=${{ env.TARGET_ARCH }}

            # Create directory if it doesn't exist
            mkdir -p ${{ env.APP_FOLDER }}
            cd ${{ env.APP_FOLDER }}

            # Pull latest code (if git repo exists)
            if [ -d .git ]; then
                git fetch origin
                git reset origin/main --hard
                git clean -dfx
            else
                # First-time clone
                git clone https://github.com/${{ github.repository }} .
            fi

            # Set up .env file ??

            docker compose down
            docker compose up -d --build

            # TODO: Clean VPS up
            # Clean docker up
            #docker system prune -f
          '